### PR TITLE
Add proper working directory to the new process

### PR DESCRIPTION
**Pull request by GeorchW**
This PR adds a proper working directory to the process, such that the spawned process can access local files, e.g. includes.

### CODE REVIEW

**Comment by eugnma** [comment]
```
{
    languageId: "org", // The language ID
    filename: "/tmp/demo.org", // The filename with full path
    extname: ".org", // The file extension
    dirname: "/tmp", // The directory name of the file path
    isUntitled: false, // Indicates a file is untitled or not
    text: "demo" // The content
}
```

Does the `dirname` meet your requirement?

**Comment by GeorchW** [comment]
No, I'd like the working directory of the new process to not be "C:/Programs/VS Code" or whatever, but the directory of the file that is opened, e.g. "D:/Thesis" (or, alternatively, the Workspace Root). This allows to write commands as 

`pandoc --css localFile.css --filter myFilter.py` 

instead of 

`pandoc --css /path/to/workspace/directory/localFile.css --filter /path/to/workspace/directory/myFilter.py`. 

That would be simpler, more intuitive, and more portable.

I'm not asking you to implement it, I just wanted to contribute a change that I made locally that I thought would make sense for more people than just me.

**Comment by GeorchW** [comment]
grafik
Looks good to me...

**Comment by eugnma** [comment]
Cool, can you help to verify the change before merging, thanks!

**Comment by GeorchW** [comment]
LGTM

**Comment by eugnma** [comment]
Please check the latest version v0.1.6 which includes the feature.

**Pull request merged**
